DROP TABLE IF EXISTS challenge.person;
CREATE TABLE challenge.person(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_date DATE NOT NULL,
    updated_date DATE,
    status_id int8,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    birth_date DATE,
    job VARCHAR(255),
    intention_change_id int8,
    actual_insurance_expire_date DATE,
    intention_insurance_ammount FLOAT,
    CONSTRAINT person_key PRIMARY KEY (id)
);

DROP TABLE IF EXISTS challenge.insurance_person;
CREATE TABLE challenge.insurance_person(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    person_id int8,
    insurance_current_id int8,
    insurance_intention_id int8,
    CONSTRAINT insurance_person_key PRIMARY KEY (id),
    CONSTRAINT person_fkey FOREIGN KEY (person_id) REFERENCES challenge.person(id)
);

DROP TABLE IF EXISTS challenge.insurance_type;
CREATE TABLE challenge.insurance_type(
     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
     description VARCHAR(255),
     CONSTRAINT insurance_type_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS challenge.intention_change_type;
CREATE TABLE challenge.intention_change_type(
     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
     description VARCHAR(255),
     CONSTRAINT intention_change_type_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS challenge.status;
CREATE TABLE challenge.status(
     id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
     description VARCHAR(255),
     CONSTRAINT status_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS challenge.insurance_accession;
CREATE TABLE challenge.insurance_accession(
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_date DATE NOT NULL,
    updated_date DATE,
    person_id int8,
    insurance_type_id int8,
    ammount FLOAT,
    start_date DATE,
    end_date DATE,
    status_id int8,
    CONSTRAINT insurance_accession_pkey PRIMARY KEY (id),
    CONSTRAINT accession_person_fkey FOREIGN KEY (person_id) REFERENCES challenge.person(id),
    CONSTRAINT accession_insurance_type_fkey FOREIGN KEY (insurance_type_id) REFERENCES challenge.insurance_type(id)
)


